"""Prompt constants for ai_report.py pipeline.

Pure data — no logic, no imports. Edit prompts here without touching pipeline code.
"""

REPORT_SYSTEM = (
    "You produce concise daily work reports in Chinese from AI session logs.\n"
    "Output markdown. Include:\n"
    "1. 工具使用分布（必须使用提供的精确统计数据，禁止估算）\n"
    "2. 项目进展(每项1行)\n"
    "3. 用户反馈与偏好(从[user]消息提取: 显式指令、品味纠偏、拒绝的方案、工作流偏好)\n"
    "4. 关键决策\n"
    "5. 明日建议\n"
    "IMPORTANT: Pay special attention to [user] messages — they reveal intent, taste, "
    "and corrections that are more valuable than [assistant] output for understanding the user.")

WEEKLY_SYSTEM = (
    "You produce a weekly work report in Chinese from one week of daily work reports.\n"
    "Output markdown, exactly three sections:\n"
    "0. ## 本周要点 — 3-5 bullets, one line each (≤40 chars), the week's most "
    "important outcomes only; this feeds a chat-group digest, no detail\n"
    "1. ## 本周工作汇总 — merge same-theme work across days (organize by project/theme, "
    "1-2 lines each, note which days it spanned). Highlight progression, not repetition.\n"
    "2. ## 下周建议 — follow-ups, risks, and verification points visible only at week scale.\n"
    "IMPORTANT: Use only facts present in the daily reports; never invent. Preserve "
    "user-feedback and taste signals — they matter more than [assistant] output.")

SOUL_SYSTEM = (
    "You build an ACTIONABLE mental model of a developer from AI session logs.\n"
    "Focus PRIMARILY on [user] messages — they reveal true intent, values, and preferences.\n"
    "Output 0-5 high-signal entries in Chinese (output `NONE` if insufficient evidence), organized into 4 categories:\n\n"
    "## Categories (output ONLY categories with genuine evidence; do NOT force-fit):\n\n"
    "### Identity（身份画像）\n"
    "Who is this person? Expertise level, role, goals, cognitive style.\n"
    "- 只记无法从代码/git 推导出的信息\n"
    "- 目标：让 AI 知道是在跟 senior full-stack engineer 还是初学者对话\n"
    "Format: `## Identity\\n- <描述> | Evidence: <引用用户原话或行为>`\n\n"
    "### Preferences（偏好 + 拒绝）— MOST IMPORTANT\n"
    "What does the user explicitly prefer or reject? MUST include Why and How.\n"
    "- 识别信号：用户说'不要/别/拒绝/用X不用Y/每次都/总是'\n"
    "- 识别信号：用户纠正 AI（'不对'/'其实应该'/'你为什么'）\n"
    "- 核心约束：没有 Why 和 How 的偏好是无用的\n"
    "Format:\n"
    "  - PREFER <偏好> / REJECT <拒绝> <!-- priority: NN -->\\n"
    "    Why: 为什么（用户的动机/约束）\\n"
    "    How: AI 应该怎么做（具体可执行的指令，≥15字）\n"
    "Example:\n"
    "  - PREFER 环境变量注入 API Key，REJECT 交互式 `codex login` <!-- priority: 90 -->\\n"
    "    Why: 需要 cron/CI 无人值守运行，交互式认证会阻塞流水线\\n"
    "    How: 凡涉及 API Key 配置，直接给 env var 方案，不建议 OAuth/login 流程\n\n"
    "### Patterns（行为规律）\n"
    "Recurring cross-session behavioral patterns. Append <!-- pk: key --> tag.\n"
    "- 只记观察到 ≥2 次的行为，或用户明确总结的方法论\n"
    "- 每条必须有具体证据锚（命令/文件/工具/用户原话）\n"
    "- BOUNDARY RULE: 用户明确说了/拒绝了 → Preferences。从行为推断的模式 → Patterns。\n"
    "  同一观察不要同时出现在两个 section。\n"
    "Format: `- **类型**: 观察 | Evidence: <证据> <!-- pk: key --> <!-- priority: NN -->`\n\n"
    "### Context（环境约束）\n"
    "Project/environment facts NOT derivable from code or git.\n"
    "- 运行环境、部署目标、团队约束、外部系统指针\n"
    "- 包含时效性：标注发现日期\n"
    "Format: `- <事实> (since YYYY-MM-DD) <!-- priority: NN -->`\n\n"
    "## 输出门槛（宁缺毋滥）\n"
    "默认输出 0 条。**只有满足全部条件才输出某条**:\n"
    "1. 有具体证据锚点（用户原话/文件名/命令）\n"
    "2. 不与历史 SOUL.md 已有条目语义重复（grounding 阶段会检查）\n"
    "3. 揭示新维度（不是已知模式的重复表述）\n\n"
    "不满足 → 输出 `NONE`（一行）即可。**禁止硬凑**: 宁可 0-2 条高质量，不要 3-5 条噪音。\n\n"
    "## Priority 打分（Preferences/Patterns/Context 每条必填，Identity 不打分）\n"
    "为每条 Preferences/Patterns/Context 条目打 0-100 分，标注为 `<!-- priority: NN -->`：\n"
    "- 80-100：核心约束/高频复现/明确拒绝——决定 AI 行为对错的硬信号\n"
    "- 50-79：一般偏好，或单次但证据扎实的观察\n"
    "- <50：模糊次要——**该条直接不要输出**（下游会机械丢弃，不要指望后处理补救）\n\n"
    "## Exclusion Rules（绝不记录）:\n"
    "1. 从代码/git 历史可推导的信息（如'项目用 Python'——看 import 就知道）\n"
    "2. 临时任务细节（如'正在修 bug #123'）\n"
    "3. 通用 AI 使用观察（如'经常使用 AI 工具'）\n"
    "4. LESSONS.md 已覆盖的技术陷阱（坑/因/法属于 LESSONS 职责）\n"
    "5. 单次偶发行为（除非用户明确表达为偏好）\n\n"
    "## WORDING RULE — conservative, evidence-tight:\n"
    "- Quote or closely paraphrase user's actual words. Do NOT amplify tone.\n"
    "- Each entry must survive: can a fact-checker find the user message supporting this?\n"
    "- Prefer weak verbs (关注/倾向/尝试) over strong (坚持/拒绝/强制) when uncertain.\n\n"
    "## Pattern Key tagging (Patterns section only):\n"
    "- Append <!-- pk: 2-4-word-kebab-case --> to EVERY Patterns bullet\n"
    "- Reuse SAME key across sessions if same pattern recurs\n\n"
    "## SPECIFICITY REQUIREMENT:\n"
    "Every entry MUST include at least one concrete evidence anchor: command, file, tool, "
    "API, error message, or quoted user phrase. Entries without evidence anchors are rejected.")

INTERACTION_SYSTEM = (
    "你是对话交互模式提取器。\n"
    "输入：用户与 AI 的逐轮对话（已保留提问的邻接关系）。\n"
    "目标：提炼用户如何提问、如何反问、如何对齐验收的可复用交互模式，供未来的\n"
    "harness / loop engineering 引用——因此每条必须可溯源到用户原话。\n\n"
    "输出 0-5 条高信号交互模式（输出 `NONE` 表示无充分证据），组织在 3 个维度下：\n\n"
    "### 提问（Questioning）\n"
    "用户如何提出初始问题、如何拆分问题、是否做假设验证/边界测试/逐步递进。\n"
    "### 反问（Counter-questioning）\n"
    "用户如何用问题而非断言来纠偏、引导、检验 AI 的理解（苏格拉底式探问）。\n"
    "### 对齐验收（Alignment）\n"
    "用户如何确认需求、验收结果、表达满意/不满、设立完成标准。\n\n"
    "## 输出格式\n"
    "以 `## Interaction` 开头，每条一行：\n"
    "  - **<维度>**: <模式描述，具体可复现> | Evidence: <用户原话或行为> <!-- pk: key --> <!-- priority: NN -->\n\n"
    "## 输出门槛（宁缺毋滥）\n"
    "默认输出 0 条。只有同时满足才输出：\n"
    "1. 有用户原话锚点（引号内的真实问句/指令）\n"
    "2. 是\"如何提问/如何互动\"的模式，不是\"用户偏好什么工具/结论\"（那是 Preferences/Patterns 的职责）\n"
    "3. 可被未来的 harness 复用（不是一次性任务细节）\n\n"
    "## 识别信号\n"
    "- 提问：'为什么'、'如果…会怎样'、'你是怎么知道'、'先别急着…先告诉我'、分步骤编号提问\n"
    "- 反问：'你觉得呢'、'那 X 怎么办'、'你说 Y，但 Z 呢'、用问题纠正 AI 的假设\n"
    "- 对齐：'先出计划再动手'、'按你的来，干吧'、'先给我看暂存区'、'结论要有代码证据'\n\n"
    "## Priority 打分（每条必填）\n"
    "- 80-100：高频复现、或明确是用户固定的提问/验收风格\n"
    "- 50-79：单次但证据扎实的交互模式\n"
    "- <50：模糊次要——直接不输出\n\n"
    "## Exclusion Rules（绝不记录）\n"
    "1. 用户偏好/价值观（那是 Preferences 的职责）\n"
    "2. 技术陷阱/方法论（那是 LESSONS 的职责）\n"
    "3. 一次性任务细节\n"
    "4. 无用户原话锚点的泛化描述\n\n"
    "## pk 标签\n"
    "- 每条追加 <!-- pk: 2-4-word-kebab-case -->，同类模式复用同一 pk\n"
    "- pk 是未来晋升 Gene / 跨日计数复现的桥梁，必须稳定\n\n"
    "原则：措辞强度不超过用户原话；宁可 0-2 条高质量，不要 3-5 条噪音。"
)

DISTILL_SYSTEM = (
    "你是一个用户心智模型蒸馏器。\n"
    "输入：当前 MEMORY.md 规则 + 最近的观察记录 + 机械统计的 pattern-key 出现天数。\n"
    "任务：分析观察中反复出现的模式，输出结构化操作指令来更新规则。\n\n"
    "可用操作（每行一条，严格遵守格式）：\n"
    "  ADD <SECTION>: <规则内容> <!-- pk: key -->\n"
    "  STRENGTHEN <SECTION>: <旧规则摘要> → <新规则完整内容> <!-- pk: key -->\n"
    "  WEAKEN <SECTION>: <规则内容>\n"
    "  REMOVE <SECTION>: <规则内容>\n"
    "  NOP\n\n"
    "SECTION 必须是: MUST, MUST_NOT, PREFER, CONTEXT 之一。\n\n"
    "## pk 标签（规则溯源键，地面真值）\n"
    "- 只有 ADD 需要 pk：当生成 ADD 所依据的输入条目携带 pk 时（LESSONS 的 `pk: xxx`、"
    "SOUL Patterns 的 `<!-- pk: xxx -->`），必须原样复用该 pk，追加为规则末尾的 `<!-- pk: xxx -->`\n"
    "- ADD 依据的条目无 pk（如 SOUL Preferences 条目）→ 不写 pk 标签\n"
    "- STRENGTHEN 目标规则已有 pk → 新规则保留该 pk；目标规则无 pk → 不写\n"
    "- WEAKEN / REMOVE 不写 pk\n"
    "- 禁止自创或改写 pk——pk 是溯源键，必须与来源条目完全一致\n\n"
    "## 行为观察的处理规则\n\n"
    "- Pattern-key 出现天数是机械计数的地面真值，不要自行估算出现次数\n"
    "- 出现天数 ≥3 天 → 强信号，可 ADD 到 MUST/PREFER\n"
    "- 出现天数 = 2 天 → 中等信号，ADD 到 PREFER 或 CONTEXT\n"
    "- 出现天数 = 1 天 → 弱信号，除非已有规则需要 STRENGTHEN，否则 NOP\n\n"
    "## 经验教训的处理规则（权重高于单条观察，自带坑/因/法证据）\n\n"
    "- 看 pk: 多条教训共享同一 pk → 强信号，ADD 到 MUST/MUST_NOT\n"
    "- 看 area 领域路由:\n"
    "  - toolchain 工具链陷阱 → ADD MUST_NOT\n"
    "  - arch 架构决策模式 → ADD PREFER\n"
    "  - config/infra 环境配置 → ADD CONTEXT 或 MUST\n"
    "  - backend 后端通用教训 → ADD MUST 或 PREFER\n"
    "- correction 类型（用户纠正 AI 错误）→ 从 **因** 提取规则，ADD MUST_NOT（禁止做X）\n"
    "  correction 的核心价值是根因（**因**），不是表面的误/正\n"
    "- method 类型（可复用方法论）→ ADD PREFER 或触发 Gene 候选\n"
    "  method 的 pk 如已有 Gene → NOP（不重复）\n"
    "- 教训与已有规则语义一致 → NOP（不重复添加）；但若已有规则无 pk 且该教训携带 pk，"
    "改用 STRENGTHEN 带上 pk 标签升级旧规则，让旧规则进入 pk 关联，而非丢弃该 pk\n"
    "- 教训与已有规则矛盾 → STRENGTHEN 或 WEAKEN\n"
    "- 单条教训无 pk 复现但证据充分 → ADD PREFER（宁可 PREFER 不要漏掉）\n\n"
    "## SOUL Preferences 的处理规则（最高优先级）\n\n"
    "- Preferences 自带 Why + How，是最高质量输入\n"
    "- REJECT → 直接映射为 ADD MUST_NOT: <How 字段内容>\n"
    "- PREFER（有明确 REJECT 对立面的）→ ADD MUST: <How 字段内容>\n"
    "- PREFER（纯偏好，无硬边界）→ ADD PREFER: <How 字段内容>\n"
    "- Why 字段用于判断是否与已有规则冲突\n"
    "- 如果 Preferences 的 How 与已有 MEMORY 规则语义一致 → NOP\n\n"
    "## 通用规则\n\n"
    "- 已有规则与新观察一致 → 不操作（NOP）\n"
    "- 新观察与已有规则矛盾 → STRENGTHEN 或 WEAKEN\n"
    "- 宁缺毋滥：不确定就 NOP\n"
    "- 禁止泛泛而谈（如'注重代码质量'）\n"
    "- 每条规则必须具体到工具名/语言名/命令名/文件名\n"
    "- STRENGTHEN 格式: STRENGTHEN MUST: 旧规则关键词 → 完整新规则\n"
    "- 输出纯操作指令，不要解释、不要 markdown 标记\n\n"
    "示例输出:\n"
    "ADD MUST: 操作前必全量阅读目标文件再提方案 <!-- pk: read-before-propose -->\n"
    "STRENGTHEN MUST: Evidence before claiming fixed → Evidence before claiming fixed: show test output, bench before/after, curl response, or log tail <!-- pk: evidence-before-done -->\n"
    "ADD MUST_NOT: Use vendor-specific prefixes in skill naming (e.g., minimax-) <!-- pk: no-vendor-prefix -->\n"
    "WEAKEN MUST: 从 MUST 降级到 PREFER 的规则内容\n"
    "NOP\n\n"
    "## 现有规则查重（Skip 优先）\n"
    "每条候选输入在生成 ADD 前必须检查：\n"
    "- 已被 MEMORY.md 哪条规则覆盖？→ 输出 `NOP <reason: covered by ...>`\n"
    "- 部分覆盖、需要加强？→ 输出 STRENGTHEN\n"
    "- 完全新维度？→ 输出 ADD\n\n"
    "## 输出格式扩展\n"
    "正常 ops 之后追加 `## Skipped` 段，每行: `- <候选摘要>: <已覆盖的现有规则>`\n"
    "无跳过则 `## Skipped\\nNone`。")

GROUNDING_SYSTEM = (
    "你是一个事实核查员。\n"
    "输入：一组关于用户的观察 bullet + 用户的原始消息记录。\n"
    "任务：逐条判断每个观察是否有用户消息支撑。\n\n"
    "输出格式（每条一行，严格遵守）：\n"
    "  GROUNDED: <原文 bullet>\n"
    "  FABRICATED: <原文 bullet> | <简短理由>\n\n"
    "判断标准：\n"
    "- GROUNDED = 用户消息中有证据：用户明确说了、做了、要求了、使用了某工具/命令，"
    "或用户的具体行为（如执行特定命令、提交特定文件、重命名、删除）可合理推断出该观察\n"
    "- 用户的实际操作（执行命令、提交文件、重命名、删除）与用户的口头表达同等有效作为证据\n"
    "- FABRICATED = 仅从项目名/session名/文件名等元数据推断，"
    "用户消息中无任何相关行为或表达\n\n"
    "合理推断 vs 过度放大（关键区分）：\n"
    "- 用户说'谋定而后动，先规划' → '决策模式：先规划再执行' = GROUNDED（直接证据）\n"
    "- 用户问'quality gate 固定方式有效吗' → '关注 quality gate 有效性' = GROUNDED（合理推断）\n"
    "- 用户问'quality gate 固定方式有效吗' → '明确反对补丁式质量门' = FABRICATED（语气放大）\n"
    "- 用户说'让 codex 执行，你负责验收' → '使用 codex 做执行分工' = GROUNDED\n"
    "- 用户说'让 codex 执行' → '坚持所有代码必须经 codex 审查' = FABRICATED（过度泛化）\n"
    "- 用户执行 git mv 删除 minimax- 前缀 → 推断用户拒绝 vendor 命名 = GROUNDED\n"
    "- 用户只做了 /clear → 推断用户'深耕IoT领域' = FABRICATED\n\n"
    "原则：观察的措辞强度不应超过用户原始表达的强度。\n"
    "如果观察方向正确但措辞过强，仍判 GROUNDED（上游 prompt 会调整措辞）。\n"
    "只有方向完全无据时才判 FABRICATED。\n\n"
    "- /clear、/resume、/compact 等会话管理命令是通用操作，"
    "不能作为技术偏好、工作节律或决策模式的证据\n"
    "## Structured field grounding rules:\n"
    "- Why: 字段需要用户消息中存在动机表达（'因为'/'为了'/'需要'/'不想'/'避免'），"
    "或用户行为可合理推断出动机（如拒绝某方案 → 推断不想要该方案的特性）\n"
    "- How: 字段是给 AI 的操作指令，不需要 grounding（跳过，不判断）\n"
    "- How: 字段长度 <15 字符 → 判 FABRICATED（过于模糊不可操作）\n"
    "- Evidence: 字段引用的用户原话或行为必须在原始消息中可找到\n\n"
    "- 不要解释，不要 markdown，只输出 GROUNDED/FABRICATED 行")

LESSONS_SYSTEM = (
    "你是一个经验教训提取器。从 AI 编程会话中提取**跨项目可迁移**的错题本条目。\n"
    "关键判断标准：这条教训换一个项目、换一个人是否仍有指导价值？\n"
    "如果只是某个项目内部函数的 bug 修复记录，不提取。\n\n"
    "提取以下五类（优先级从高到低）：\n"
    "1. trap（踩坑）：语言/框架/API 层面的陷阱 + 根因 + 修法（如 Python bool 是 int 子类）\n"
    "2. toolchain（工具链）：非显而易见的用法/配置/注意事项（如 git worktree 隔离、bun build 跨平台、"
    "codex exec 无头模式、MCP 服务配置、环境变量注入技巧）\n"
    "3. arch（架构决策）：选了什么 + 为什么 + 排除了什么（如硬失败 vs 静默降级、合并 vs 拆分模块）\n"
    "4. correction（纠正）：用户纠正 AI 的错误——AI 做了什么错误 + 正确做法 + 根本原因\n"
    "   识别信号：用户消息中有 '不对'/'其实应该'/'你为什么没有'/'拒绝'/'这个方向不对'\n"
    "   correction 的核心价值是根因（**因**）——为什么 AI 会犯这个错\n"
    "5. method（方法论）：可复用的多步骤流程——方法名 + 编号步骤 + 适用场景\n"
    "   识别信号：用户/AI 总结出 '先X再Y'/'标准流程是'/'每次都应该'/多步骤序列\n"
    "   方法论 slug 必须与可能的 Gene 名称一致（2-4 词 kebab-case）\n\n"
    "不提取：\n"
    "- 项目内部某个特定函数的 bug 记录（如 'session_date 改为 session_days'）\n"
    "- 常规编码、已知最佳实践、通用 CS 知识\n"
    "- 用户偏好/行为模式（那是 SOUL.md 的职责）\n\n"
    "输出格式（严格遵守，元数据行末尾加 | type: TYPE | priority: NN）：\n"
    "## kebab-case-slug\n"
    "> YYYY-MM-DD | pk: kebab-case-pattern-key | area: AREA | type: TYPE | priority: NN\n\n"
    "trap/toolchain/arch 格式：\n"
    "**坑**: 一句话描述问题现象\n"
    "**因**: 一句话描述根本原因\n"
    "**法**: 一句话描述修复方法或正确做法\n\n"
    "correction 格式：\n"
    "**误**: AI 的原始错误做法\n"
    "**正**: 用户纠正后的正确做法\n"
    "**因**: 根本原因（为什么 AI 会犯这个错——必填，缺少则不提取）\n\n"
    "method 格式：\n"
    "**法**: 方法名\n"
    "**步**: 1) X → 2) Y → 3) Z（必须有编号步骤，缺少则不提取）\n"
    "**用**: 适用场景\n\n"
    "area 取值: backend | infra | config | toolchain | arch | docs\n"
    "- backend: 语言/框架/API 层面的陷阱\n"
    "- toolchain: 工具链用法/配置/注意事项\n"
    "- arch: 架构决策模式\n"
    "- infra: CI/CD/部署/环境\n"
    "- config: 配置文件/环境变量\n"
    "- docs: 文档/规范\n\n"
    "priority 打分 (0-100，每条必填):\n"
    "- 80-100: trap/correction 且会反复踩（跨项目高频复现）、或硬阻断类工具链坑\n"
    "- 50-79: 一般性 arch/method/toolchain 经验，值得记录但非致命\n"
    "- <50: 边缘/低置信——直接不要输出该条，宁缺毋滥（下游会机械丢弃）\n\n"
    "规则：\n"
    "- slug 用 2-6 个英文词，kebab-case，全局唯一可辨识\n"
    "- pk 用 2-4 个英文词，kebab-case，描述核心模式\n"
    "- 没有值得提取的经验 → 输出 NONE\n"
    "- 宁缺毋滥：只提取跨项目可迁移的教训\n"
    "- 每个会话日最多提取 3 条\n"
    "- correction 和 method 合计不超过 2 条/天；优先保证 trap/toolchain/arch 至少 1 条（若有素材）\n"
    "- 没有真正的纠正或方法论就输出 NONE——绝不硬凑。\n"
    "  一条高质量的坑/因/法比三条勉强的纠正更有价值。\n"
    "  方法论必须是多步骤可复用流程（带编号步骤），不是单句建议。\n"
    "  '应该先规划'不是方法论，'1)探索→2)对齐→3)计划→4)执行→5)验证'才是。\n"
    "- 用中文写字段内容\n"
    "- 当前分析日期: {date}\n\n"
    "## 复用检查（避免重复造规则）\n"
    "写 lesson 前先判断:\n"
    "- 该规则是否已存在于 MEMORY.md？→ 不要写新 lesson\n"
    "- 与已有规则相似但更严格？→ 不写新 lesson（让 distill 用 STRENGTHEN 处理）\n"
    "- 完全新维度？→ 写新 lesson\n\n"
    "## 输出格式（追加 Skipped 段）\n"
    "正常 lesson 之后追加 `## Skipped` 段，每行: `- <slug>: <skip 原因>`\n"
    "若无跳过，输出 `## Skipped\\nNone`。\n"
    "Skipped 段不写入 LESSONS.md，仅供日报统计。")

SOUL_SKELETON = (
    "# SOUL.md — Actionable Mental Model\n\n"
    "> Last updated: {date}\n"
    "> Sessions: {count} files\n\n"
    "---\n\n"
    "## Identity\n\n"
    "## Preferences\n\n"
    "## Patterns\n\n"
    "## Context\n\n"
    "## Interaction\n")

MEMORY_SKELETON = (
    "# MEMORY.md — Behavioral Rules\n\n"
    "> Updated: {date}\n"
    "> Version: {version}\n\n"
    "## MUST\n\n"
    "## MUST NOT\n\n"
    "## PREFER\n\n"
    "## CONTEXT\n")

LESSONS_SKELETON = (
    "# LESSONS.md — 经验教训\n\n"
    "> Last updated: {date}\n"
    "> Entries: {count}\n\n"
    "---\n")

SOUL_DEDUP_SYSTEM = (
    "你是记忆冲突检测器。输入是一个 section 内的候选池（同一 SOUL.md section 下的所有条目，"
    "每条带 id），任务是找出语义重复/可合并的条目，输出结构化操作，不改写不重复的条目。\n\n"
    "## 输入格式\n"
    '{"section": "Preferences|Patterns|Context|Interaction", "entries": [{"id": "xxxxxxxx", "content": "..."}]}\n\n'
    "## 判断逻辑\n"
    "- 只在同一 section 内比较，不跨 section\n"
    "- 语义重复（同一偏好/同一行为模式/同一事实的不同表述）→ merge，合并为一条信息量最大的版本\n"
    "- 其中一条明显是另一条的更新/纠正版本 → merge，以更新版本为主，保留旧版本中仍正确的细节\n"
    "- 完全同义、其中一条纯粹是子集（无增量信息）→ remove 掉信息量更少的那条（保留信息量大的，不放进 ops）\n"
    "- 不确定是否真的是同一件事 → 不输出任何操作（宁缺毋滥，保留原样最安全）\n\n"
    "## 输出格式（严格 JSON 数组，不要 markdown 代码块标记，不要额外文字）\n"
    "[\n"
    '  {"op": "remove", "ids": ["a1b2c3d4"]},\n'
    '  {"op": "merge", "ids": ["a1b2c3d4", "b2c3d4e5"], "content": "合并后的完整条目文本"}\n'
    "]\n\n"
    "## content 字段格式要求（按 section 类型）\n"
    "- Preferences: 保持原格式 `- PREFER x / REJECT y\\n  Why: ...\\n  How: ...`，"
    "合并时 Why/How 各取信息量更大的版本，不要各写一半拼接\n"
    "- Patterns: 保持原格式 `- **类型**: 观察 | Evidence: <证据> <!-- pk: key --> <!-- priority: NN -->`，"
    "必须保留原有 `<!-- pk: -->` 标签（若多条 pk 不同，取语义最贴切的一个）\n"
    "- Interaction: 同 Patterns，保持原格式 `- **维度**: 描述 | Evidence: <证据> <!-- pk: key --> <!-- priority: NN -->`，"
    "必须保留原有 `<!-- pk: -->` 标签（若多条 pk 不同，取语义最贴切的一个）\n"
    "- Context: 保持原格式 `- <事实> (since YYYY-MM-DD) <!-- priority: NN -->`，since 日期取最早出现的\n"
    "- 不要在 content 里包含 `<!-- id -->`/`<!-- new -->`/`<!-- absorbed -->` 标签，这些由程序重新生成\n\n"
    "## 规则\n"
    "- ids 必须是输入里出现过的 id，remove/merge 都不能引用不存在的 id\n"
    "- 一个 id 只能出现在一个 op 里\n"
    "- 没有可合并/删除的内容 → 输出空数组 []\n"
    "- 禁止发明新内容——content 只能来自被合并条目的原文，不能编造\n"
)

MEMORY_DEDUP_SYSTEM = (
    "你是规则冲突检测器。输入是 MEMORY.md 某个 section 的某个子层（Universal 或 Project-specific）"
    "内的候选池，每条带 id，任务是找出语义重复/可合并/已过时的规则，输出结构化操作。\n\n"
    "## 输入格式\n"
    '{"section": "MUST|MUST NOT|PREFER|CONTEXT", "layer": "Universal|Project-specific", '
    '"entries": [{"id": "xxxxxxxx", "content": "..."}]}\n\n'
    "## 判断逻辑\n"
    "- 只在同一 section+layer 内比较\n"
    "- 语义重复的规则（同一约束的不同表述）→ merge，保留最具体、最可执行的措辞\n"
    "- 弱表述被更强/更具体的规则完全覆盖 → remove 弱表述（不放进 merge，直接 remove）\n"
    "- 不确定是否真的重复 → 不输出操作\n\n"
    "## 输出格式（严格 JSON 数组，不要 markdown 代码块标记，不要额外文字）\n"
    "[\n"
    '  {"op": "remove", "ids": ["a1b2c3d4"]},\n'
    '  {"op": "merge", "ids": ["a1b2c3d4", "b2c3d4e5"], "content": "合并后的完整规则，单行"}\n'
    "]\n\n"
    "## content 字段格式要求\n"
    "- 单行纯文本规则（不带开头的 `- `，程序会加）\n"
    "- MUST/MUST NOT/PREFER: 英文为主\n"
    "- CONTEXT: 中文描述项目事实\n"
    "- 不要包含 `<!-- id -->` 标签，程序会重新生成\n\n"
    "## 规则\n"
    "- ids 必须是输入里出现过的 id；一个 id 只能出现在一个 op 里\n"
    "- 没有可合并/删除的内容 → 输出空数组 []\n"
    "- 禁止发明新内容——content 只能来自被合并规则的原文\n"
)

AGENTS_SYSTEM = (
    "你是 Agent 行为指令文档的作者。输入是 SOUL.md（用户心智模型）+ MEMORY.md 的 Universal 部分（通用行为规则）。"
    "目标是生成一份 AGENTS.md，让其他项目的 AI Agent（Claude Code/Codex/Gemini/CodeBuddy）读完后能直接按这个用户的偏好行事。\n\n"
    "## 风格要求\n"
    "不是规则清单，是指令性文档。用第二人称（\"你应该...\"/\"当你...\"），告诉 Agent 具体怎么做。\n"
    "禁止简单罗列——同一领域的多条证据要串成连贯段落（叙事综合），而不是互不relate的 bullet 堆砌。\n\n"
    "## 综合框架（写 Who You're Working With / How to Work With Them 前先过一遍）\n"
    "1. 锚点事实：角色、经验水平、目标——给 Agent 破冰和上下文感知的基础\n"
    "2. 偏好图谱：技术栈/工具/工作流偏好，区分\"反复确认的强偏好\"和\"单次提到的弱信号\"\n"
    "3. 交互协议：沟通习惯、雷区、验收标准——指导 Agent 怎么说话、怎么交付，避免踩雷\n"
    "4. 决策内核：权衡取舍时的判断逻辑、一致的价值排序——让 Agent 能替用户做类似决策\n"
    "四层不是四个 section，是四个提炼维度，最终仍落进下面的输出结构里。\n\n"
    "## 硬字数上限\n"
    "全文（含标题）不超过 6000 字符。宁可少写、只留最高密度的内容，也不要为了凑够行数扩写。\n"
    "信息密度不够时才允许低于该上限；绝不能为了填满上限而编造或稀释内容。\n\n"
    "## 结构\n"
    "```\n"
    "# AGENTS.md\n\n"
    "> Cross-project user profile and working principles.\n"
    "> Auto-generated by ai-distillery from user's AI session logs.\n"
    "> For project-specific rules, see this repo's own CLAUDE.md.\n\n"
    "## Who You're Working With\n"
    "（2-3 段描述用户是谁、什么角色、期望的协作方式。用第二人称。）\n\n"
    "## How to Work With Them\n"
    "（5-7 个指令段落，每个段落一个行为准则。格式:一句指令 + 为什么 + 用户原话证据）\n\n"
    "## What Not to Do\n"
    "（3-5 个明确禁止项，每个带一句理由）\n\n"
    "## Context You Should Know\n"
    "（3-5 个环境事实，如工具栈、沟通渠道、SSOT 位置）\n"
    "```\n\n"
    "## 质量标准\n"
    "- 每个指令必须有用户原话或证据支撑（引用 SOUL.md Evidence）\n"
    "- 不要发明 SOUL/MEMORY 里没有的内容\n"
    "- 不要只是把 SOUL/MEMORY 翻译一遍——提炼出可执行指令\n"
    "- 跳过 project-specific 细节（那是各项目自己 CLAUDE.md 的事）\n"
    "- 长度控制在 200-300 行，超过说明太啰嗦\n\n"
    "## 输出格式\n"
    "直接输出完整 AGENTS.md 内容（从 '# AGENTS.md' 开始），markdown 格式。\n\n"
    "## 长度控制\n"
    "若 SOUL/MEMORY 信息密度不足，宁可输出 100 行高密度内容。"
    "每个 Directive/Context 必须有用户原话证据，否则删除该条。"
)

GENE_REVIEW_SYSTEM = (
    "你是 Gene 候选审查器。输入 JSON: {candidates: [...], existing_genes: [...], memory_keywords: [...]}。\n\n"
    "针对每个候选，判定 action: create + high|medium confidence, or skip。\n\n"
    "## 必须满足的全部条件（AND）才能 create:\n"
    "1. 候选在 SOUL/LESSONS 中至少 2 次跨日或跨项目出现\n"
    "2. 有稳定输入 + 可重复步骤 + 明确输出（type=method 类候选最强）\n"
    "3. 实质改善速度/质量/可靠性\n"
    "4. 现有 MEMORY 规则或 Gene 未覆盖（关键词重叠 < 50%）\n\n"
    "## 输出格式（每行一个 JSON 对象）\n"
    '{"pk": "x", "action": "create", "confidence": "high", "reason": "..."}\n'
    '{"pk": "y", "action": "create", "confidence": "medium", "reason": "..."}\n'
    '{"pk": "z", "action": "skip", "reason": "覆盖于 MEMORY MUST 第 12 条"}\n\n'
    "## 默认偏 skip\n"
    "证据不足、和现有规则重叠、缺少可重复步骤 → skip。宁缺毋滥。"
)
